### ISSUE TITLE
Upload Files to Class Server

### ISSUE THREAD

**Issue by danZzyy** [danZzyy/WebGISNTL#1]
1. We must decide on the regional subset of our data. I really don't care what we choose so lets just pick something.
2.  We must upload the files to the classes ArcGIS server

the files can be found here: https://umd.app.box.com/s/alf4lycvl1p283olt8h972ffese54zjz

**Comment by jonnyboy2040** [comment]
Uploaded Sub-Saharan Africa dataset including the raster .tiff, the admin boundaries, the 1996 and 2010 NTL, and the master extent. 

https://129.2.6.223:6443/arcgis/rest/services/GEOG498K2016/HAO_NTL_DATA/MapServer
