### ISSUE TITLE
Basemap loading

### ISSUE THREAD

**Issue by danZzyy** [danZzyy/WebGISNTL#8]
The basemap does not render, much like on the labs. I checked documentation and it looks like we have it right
```
  var map = new Map({
    basemap: "oceans"
  });
```
Lets try to look into this and see if it is worth our time. I think any Web GIS system should have a basemap to be taken seriously.

**Comment by jonnyboy2040** [comment]
It's not loading because we're running our project from local machines, not from a hosted server. Need to upload project to class-provided server. 

See this file: 
[GEOG498KFall2016ServerInfo.pdf](https://github.com/danZzyy/WebGISNTL/files/617272/GEOG498KFall2016ServerInfo.pdf)

**Comment by jonnyboy2040** [comment]
Basemap's working properly when uploaded to the server.
